name = "Anville"
author = "Khazoda"
version = "1.2.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c694d2b0e262b63982411dead2394a11a744dd36c4960d1407884b6639fdfebb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "basicweapons_materialpacks/"
no-internal-hashes = ["resourcepacks/*"]
