name = "Anville"
author = "Khazoda"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0b44eea4f70b2be97b74ea56ef480a76a9d97efa738122c581dc2b80b75f307"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "basicweapons_materialpacks/"
no-internal-hashes = ["resourcepacks/*"]
