name = "Anville"
author = "Khazoda"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b23976a670ce6464c840ef98fec0a07f322d345554f23bb9d79c172d3db59642"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "basicweapons_materialpacks/"
no-internal-hashes = ["resourcepacks/*"]
