name = "Anville"
author = "Khazoda"
version = "1.2.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c41afec5d4a38edc184b815f9713267352e9ac851deea977f21994ffe1d319fa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "basicweapons_materialpacks/"
no-internal-hashes = ["resourcepacks/*"]
