name = "Anville"
author = "Khazoda"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e56619d8848b675b7c2edb461b235cc2d4a40e60f50b8976f4a9be5b81ba8235"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "basicweapons_materialpacks/"
no-internal-hashes = ["resourcepacks/*"]
